# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lyf.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gini = QtWidgets.QPushButton(self.centralwidget)
        self.gini.setGeometry(QtCore.QRect(40, 250, 171, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        self.gini.setFont(font)
        self.gini.setObjectName("gini")
        self.entopy = QtWidgets.QPushButton(self.centralwidget)
        self.entopy.setGeometry(QtCore.QRect(30, 370, 171, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        self.entopy.setFont(font)
        self.entopy.setObjectName("entopy")
        self.csv = QtWidgets.QPushButton(self.centralwidget)
        self.csv.setGeometry(QtCore.QRect(30, 10, 301, 91))
        self.csv.setObjectName("csv")
        self.xlsx = QtWidgets.QPushButton(self.centralwidget)
        self.xlsx.setGeometry(QtCore.QRect(30, 110, 301, 91))
        self.xlsx.setObjectName("xlsx")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(350, 10, 421, 531))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "林怡凡"))
        self.gini.setText(_translate("MainWindow", "gini"))
        self.entopy.setText(_translate("MainWindow", "entopy"))
        self.csv.setText(_translate("MainWindow", "输入数据 CSV文件"))
        self.xlsx.setText(_translate("MainWindow", "输入数据 xlsx文件"))
